import storygenerator as generator
import nltk

nltk.download('punkt')

story_generator = generator.StoryGenerator("Story generated by using Story Grammars")

"""
# Defining a rule
sg.addrule('NAME OF RULE', {'Content of Rule'})

# Rule with multiple alternatives to choose from
sg.addrule('NAME OF RULE', {'option A', 'option B'})

# Summon other rule within a rule (use * to delimit rule name)
sg.addrule('BIGRULE', {' This is to use the *SMALLRULE* and rewrite'})
sg.addrule('SMALLRULE', {'small rule', 'tiny rule'})
"""

story_generator.reset()  # clear the story generator

# base rule
story_generator.addrule('STORY', {"*INTRODUCTION*. *RISE*. *CRISIS*. *CLIMAX*. *ENDING*."})

story_generator.addrule('INTRODUCTION', {"*TIME_STORY*, there was a *CHARACTER* that *VERB* to be *DIRECT_OBJECT*."})

story_generator.addrule('RISE', {"For that, they need to go to *PLACE* and find *PERSON* to help accomplish their goal."
                                 " During the journey, they learn how to *ABILITY*, which lead to *DISEASE*"})

story_generator.addrule('CRISIS', {"*ADVERS_CONJ*, there was no one when they finally reach the destination - only a "
                                   "*THING*"})

story_generator.addrule('CLIMAX', {"Feeling sad, they wanted *GOAL* to appease the pain. And when everything seemed "
                                   "to be lost, a voice was heard: it came from the only thing that was giving them "
                                   "some company. It seemed that it was the person they were looking for! He told he "
                                   "was bewitched for *REASON*."})

story_generator.addrule('ENDING', {"In the end, the protagonist *RESULT*"})

story_generator.addrule('TIME_STORY', {'Once upon a time', 'Long ago', 'In a land far away', 'In days of yore',
                                       'In the beginning', 'Many years ago', 'Ages ago', 'Once', 'In a time long past',
                                       'In ancient times',
                                       'In a distant era', 'In a bygone era', 'In a time of legends',
                                       'In a world of fantasy',
                                       'In a world of dreams', 'In a world of imagination', 'In a realm of enchantment',
                                       'In a kingdom far away',
                                       'In a far-off land', 'In a lost world', 'In a forgotten land',
                                       'In a world of make-believe',
                                       'In a world of fable', 'In a world of fiction', 'In a world of tale',
                                       'In a world of lore'})

story_generator.addrule('CHARACTER', {"""*AGE* *PROFESSION* *GENDER*"""})

story_generator.addrule('AGE', {'young', 'old'})
story_generator.addrule('PROFESSION', {"doctor", "teacher", "chef", "mechanic", "lawyer", "artist", "scientist",
                                       "architect", "athlete", "entrepreneur", "nurse", "programmer", "musician",
                                       "writer", "actor", "politician", "engineer", "journalist", "psychologist",
                                       "designer"})

story_generator.addrule('GENDER', {'male', 'female'})

story_generator.addrule('VERB', {"arrived",
                                 "wanted",
                                 "needed",
                                 "desired"
                                 "stopped",
                                 "retired",
                                 "danced",
                                 "laughed",
                                 "collapsed",
                                 "played",
                                 "sneezed",
                                 "fainted",
                                 "talked",
                                 "walked",
                                 "coughed",
                                 "traveled",
                                 "died",
                                 "yelled",
                                 "climbed",
                                 "smiled",
                                 "slipped",
                                 "floated",
                                 "wavered",
                                 "leaned",
                                 "appeared",
                                 "disappeared",
                                 "rejoiced",
                                 "hovered",
                                 "cried",
                                 "gasped",
                                 "rested",
                                 "shivered",
                                 "groaned",
                                 "sneered",
                                 "nodded",
                                 "swayed",
                                 "stumbled",
                                 "buzzed",
                                 "glowed",
                                 "staggered",
                                 "whispered",
                                 "moaned",
                                 "skated"})

story_generator.addrule('DIRECT_OBJECT', {"a book",
                                          "a sandwich",
                                          "a phone",
                                          "a movie",
                                          "a glass of water",
                                          "a car",
                                          "a backpack",
                                          "a cake",
                                          "a new computer",
                                          "a newspaper",
                                          "his guitar",
                                          "a cup of coffee",
                                          "the dog",
                                          "a bright idea",
                                          "their luggage",
                                          "the letter",
                                          "a warm blanket",
                                          "the camera",
                                          "a fresh salad",
                                          "the painting",
                                          "the patient",
                                          "a difficult essay",
                                          "a delicious meal",
                                          "a broken engine",
                                          "a compelling argument",
                                          "a beautiful landscape",
                                          "a groundbreaking experiment",
                                          "an innovative building",
                                          "a grueling marathon race",
                                          "a successful startup company",
                                          "a comfortable chair",
                                          "a shiny diamond",
                                          "a colorful painting",
                                          "a powerful computer",
                                          "a refreshing drink",
                                          "a challenging puzzle",
                                          "a relaxing massage",
                                          "a shiny trophy",
                                          "a mysterious envelope",
                                          "a beautiful flower",
                                          "a good person",
                                          "a villain",
                                          "a teacher",
                                          "a dog",
                                          "a banana"})

story_generator.addrule('PLACE', {"Tokyo", "The Shire", "Paris", "Neverland", "The Moon", "Narnia", "Atlantis", "Rome",
                                  "Hogwarts", "The Amazon Rainforest", "Mars", "The Bermuda Triangle", "Mount Everest",
                                  "El Dorado", "The North Pole", "Wakanda", "The Great Barrier Reef", "Asgard",
                                  "The Underworld", "Shangri-La", "castle", "river", "bridge", "mountain", "cave",
                                  "beach",
                                  "forest", "desert", "waterfall", "valley", "island", "cemetery", "volcano", "ocean",
                                  "swamp",
                                  "lake", "park", "farm", "city", "jungle"})

story_generator.addrule('PERSON', {"Alewife (brewer)", "Alchemist", "Astrologer", "Barber-surgeon", "Court jester",
                                   "Falconer", "Fletcher (arrow maker)", "Gong farmer (sewer cleaner)", "Herald",
                                   "Lector (professional reader)", "Plague doctor", "Rat catcher", "Scribe",
                                   "Tollund Man (sacrifice)", "Whipping boy", "Witch hunter", "Soothsayer",
                                   "Candlemaker",
                                   "Leper", "Pardoner", "Astrologer", "Alchemist", "Necromancer", "Sorcerer", "Diviner",
                                   "Occultist", "Demonologist", "Exorcist", "Witch", "Warlock", "Herbalist", "Magician",
                                   "Alchemy assistant", "Dowser", "Crystal gazer", "Medium", "Spiritualist",
                                   "Apotropaist",
                                   "Thaumaturge", "Geomancer", "Astrologer-astronomer", "Cleromancer", "Pyromancer",
                                   "Transmutationist", "Psychomancer", "Demon summoner", "Voodoo priest", "Nigromancer",
                                   "Occult philosopher", "Inquisitor", "Chaos magician", "Soothsayer", "Magus",
                                   "Conjurer",
                                   "Esotericist", "Hermetist", "Grimoire writer", "Hedge witch", "Ceremonial magician"})

story_generator.addrule('ABILITY', {"recite the alphabet backward", "touch their nose with their tongue", "wiggle "
                                                                                                         "their "
                                                                                                         "ears",
                                   "hold their breath for 2 minutes", "balance a spoon on their nose", "make a clover "
                                                                                                       "shape with "
                                                                                                       "their "
                                                                                                       "tongue",
                                   "spin a book on their finger", "do a cartwheel", "tie a cherry stem with their "
                                                                                    "tongue", "blow a bubblegum "
                                                                                              "bubble bigger than "
                                                                                              "their head",
                                   "lick their elbow", "juggle 3 balls", "make a bird call with their hands",
                                   "roll their tongue", "make their eyes vibrate", "do a handstand", "fold a fitted "
                                                                                                     "sheet "
                                                                                                     "perfectly",
                                   "whistle with their fingers", "do a backflip", "play the kazoo with their nose"})

story_generator.addrule('DISEASE', {"Exploding head syndrome", "Alice in Wonderland syndrome",
                                    "Foreign accent syndrome", "Koro syndrome", "Capgras delusion", "Jerusalem syndrome",
                                    "Walking corpse syndrome", "Paris syndrome", "Urbach-Wiethe disease",
                                    "Morgellons disease", "Cotard delusion", "Alien hand syndrome",
                                    "Body integrity dysphoria", "Stendhal syndrome", "Werewolf syndrome",
                                    "Stone man syndrome", "Fish odor syndrome", "Sleeping beauty syndrome",
                                    "Tree man syndrome", "Boanthropy", "Cancer", "Alzheimer's disease",
                                    "Heart disease", "Stroke", "Diabetes", "Influenza", "Parkinson's disease",
                                    "Hepatitis B and C", "HIV/AIDS", "Malaria", "Lupus", "Rheumatoid arthritis",
                                    "Chronic obstructive pulmonary disease (COPD)", "Eczema", "Gout", "Fibromyalgia",
                                    "Irritable bowel syndrome (IBS)", "Psoriasis", "Celiac disease",
                                    "Tourette's syndrome", "Osteoporosis", "Glaucoma", "Tuberculosis", "Epilepsy",
                                    "Multiple sclerosis (MS)", "Scoliosis", "Huntington's disease", "Lyme disease",
                                    "Cushing's syndrome", "Polycystic ovary syndrome (PCOS)", "Endometriosis",
                                    "Hemophilia", "Wilson's disease", "Porphyria", "Hypothyroidism", "Hyperthyroidism",
                                    "Narcolepsy", "Sleep apnea", "Restless legs syndrome", "Color blindness"})

story_generator.addrule('ADVERS_CONJ', {"But", "Suddenly", "Meanwhile", "All of a sudden", "Abruptly", "Unexpectedly",
                                        "Out of the blue", "Without warning", "Suddenly and without warning",
                                        "At a moment's notice", "In an instant", "In the blink of an eye",
                                        "In a split second", "Instantaneously", "Immediately", "Quickly", "Swiftly"})

story_generator.addrule('THING', {"book", "car", "computer", "chair", "table", "phone", "water", "food", "house",
                                  "plant", "shoe", "animal", "bike", "TV", "door", "window", "lamp", "bag", "shirt",
                                  "clock"})

story_generator.addrule('GOAL', {"to commit suicide", "ice cream", "a pair of shoes", "to disappear into the void",
                                 "a hot cup of tea", "to go back in time", "a warm hug", "a soft blanket",
                                 "to be alone", "to run away", "to forget", "to be held", "to be comforted", "to cry",
                                 "to scream", "to disappear", "to feel better", "to be understood", "to escape",
                                 "to sleep forever", "to be numb", "to turn back time", "to be happy again",
                                 "to be loved", "to start over", "to be free", "to be accepted", "to find peace",
                                 "apple", "banana", "cheeseburger", "chicken", "chips", "chocolate", "cookie",
                                 "croissant", "donut", "eggs", "grilled cheese", "hamburger", "hot dog", "ice cream",
                                 "pizza", "popcorn", "ramen", "sandwich", "taco", "waffles"})

story_generator.addrule('REASON', {"sleeping with a nurse", "eating chocolate out of date", "running in the park",
                                   "singing a sad song", "dancing in the rain", "cooking a delicious meal",
                                   "laughing uncontrollably", "reading a good book", "writing a novel",
                                   "painting a beautiful picture", "playing a musical instrument",
                                   "learning a new skill", "sleeping peacefully", "watching a movie",
                                   "listening to music", "talking to a friend", "traveling the world",
                                   "hiking in the mountains", "swimming in the ocean",
                                   "cycling through the countryside", "gardening in the backyard",
                                   "meditating in a quiet place", "sneeze uncontrollably in public",
                                   "singing off-key karaoke in an empty bar", "dancing the robot at a funeral",
                                   "running with scissors", "eating a whole cake with no hands",
                                   "yawning while talking to your boss", "laughing at inappropriate times",
                                   "crying over spilled milk", "jumping into a pool of jello",
                                   "shouting into a pillow underwater", "sleeping during a job interview",
                                   "burping the alphabet in a fancy restaurant", "farting on a crowded elevator",
                                   "daydreaming during a first date", "drawing on a stranger's face while they sleep",
                                   "texting while riding a unicycle", "brushing your teeth with hot sauce",
                                   "hugging a cactus", "swimming in a pool of pudding", "smoking a lollipop"})

story_generator.addrule('RESULT', {"was admitted to a psychiatric hospital for having hallucinations",
                                   "and the object became friends", "and the object became lovers",
                                   "ate the object", "sold the object to an institution", "buried himself alive",
                                   "woke up", "fell asleep", "went to an isekai world", "met Cristina Ferreira"})

story_generator.entrypointrule('STORY')

# generates the story
story_generator.generate()
print('*'*20)
output_story = str(story_generator)
story_sent = nltk.tokenize.sent_tokenize(output_story)

for sent in story_sent:
    print(sent)

